// <auto-generated />
namespace Bware.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class temp_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(temp_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201507181101346_temp_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
