// <auto-generated />
namespace Bware.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_country_weightdouble_to_bridge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_country_weightdouble_to_bridge));
        
        string IMigrationMetadata.Id
        {
            get { return "201507171839397_Added_country_weightdouble_to_bridge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
