// <auto-generated />
namespace Bware.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_WeightStraight_TriAxle_to_bridge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_WeightStraight_TriAxle_to_bridge));
        
        string IMigrationMetadata.Id
        {
            get { return "201510182344040_Add_WeightStraight_TriAxle_to_bridge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
