// <auto-generated />
namespace Bware.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_isActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_isActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201509252340457_Add_isActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
